version: '3.8'
services:
  paperless-rest:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: paperless-rest
    ports:
      - "8081:8081"
    volumes:
      - ../WebApplicationSWEN3:/app
    working_dir: /app
    command: ["dotnet", "run", "--urls", "http://0.0.0.0:8081"]
    networks:
      - paperless-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=documentsearch;Username=mamo;Password=T1P3m!hvQ9

  paperless-webui:
    image: nginx:alpine
    container_name: paperless-webui
    ports:
      - "80:80"
    volumes:
      - ../paperlessWebUI:/usr/share/nginx/html
      - ../paperlessWebUI/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - paperless-network

  postgres:
    image: postgres:13
    container_name: paperless-postgres
    environment:
      POSTGRES_USER: mamo
      POSTGRES_PASSWORD: T1P3m!hvQ9
      POSTGRES_DB: documentsearch
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - paperless-network

networks:
  paperless-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
