version: '3.8'
services:
  paperless-rest:
    build:
      context: ../
      dockerfile: Docker/Dockerfile  
    container_name: paperless-rest
    ports:
      - "8081:8081"
    networks:
      - paperless-network
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=paperless-postgres;Port=5432;Database=documentsearch;Username=mamo;Password=T1P3m!hvQ9

  paperless-webui:
    image: nginx:alpine
    container_name: paperless-webui
    ports:
      - "80:80"
    volumes:
      - ../paperlessWebUI:/usr/share/nginx/html
      - ../paperlessWebUI/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - paperless-network

  paperless-postgres:
    image: postgres:13
    container_name: paperless-postgres
    environment:
      POSTGRES_USER: mamo
      POSTGRES_PASSWORD: T1P3m!hvQ9
      POSTGRES_DB: documentsearch
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - paperless-network


  rabbitmq:
    image: rabbitmq:3.9.29-management-alpine
    ports:
        - 5672:5672
        - 9093:15672
    environment:
      RABBITMQ_DEFAULT_USER: user      
      RABBITMQ_DEFAULT_PASS: password 
    networks:
      - paperless-network


networks:
  paperless-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
